name: Build and Release Debian Package
on:
  workflow_call:
    inputs:
      apt_repo:
        description: 'The apt repository (e.g. michal-maruska/apt-repo)'
        type: string
        default: "michal-maruska/apt-repo"
      ref:
        description: 'Branch, tag or SHA to checkout'
        type: string
        default: 'main'
      architectures:
        description: 'Architectures to build for'
        type: string
        default: 'amd64'  # or 'amd64,arm64'
    secrets:
      PAT_TOKEN:
        required: true

permissions:
  contents: write
  packages: write # Optional, but good if you use GHCR

jobs:

  update-changelog:
    runs-on: ubuntu-latest
    # gbp dch, commit changelog
    # outputs: version string
    outputs:
      version: ${{ steps.version.outputs.version }}
      tag_name: ${{ steps.version.outputs.tag_name }}
    steps:
      - name: Update Changelog (dch)
        env:
          DEBEMAIL: "mmaruska+deb@gmail.com"
          DEBFULLNAME: "Michal Maruska"
        run: |
          # mess with permissions/ownership: actions/checkout works outside the container
          # su builder -c "git config --global --add safe.directory ."
          # 2. Fix permissions (GitHub Actions mounts the repo as root)
          chown -R builder:builder .
          # --snapshot: creates a temporary version (useful for CI)
          # --release: prepares it for a real release
          # --auto: tries to guess the next version number based on tags
          # su builder -c "gbp --list-cmds"
          # su builder -c "which dch"
          su builder -c "gbp dch --release --auto --ignore-branch --spawn-editor=never"

      - name: Extract Version and Tag
        id: version
        run: |
          # Extract the version string (e.g., 1.2.3-1)
          VERSION=$(dpkg-parsechangelog -S Version)
          # cannot use :
          SAFE_VERSION=$(echo "$VERSION" | sed 's/:/_epoch/g; s/~/_/g')
          DISTRIBUTION=$(dpkg-parsechangelog -S Distribution)
          TAG_NAME="$DISTRIBUTION/$SAFE_VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT


  build-amd64-and-indep:
    needs: update-changelog
    runs-on: ubuntu-latest
    container:
      # this is what we build for: SID
      image:  ghcr.io/${{ github.repository_owner }}/debian-builder:main
      # for now the image is not public ...
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          # mmc: full.
          # todo: up to previous tag
          fetch-depth: 0 # Get all history for tagging


      - name: Install dependencies
        run: |
          apt-get update
          # 3. Install build-deps (this still needs root)
          mk-build-deps --install --remove --tool="apt-get -y --no-install-recommends" debian/control
          # rm -f *-build-deps_*.deb

      - name: fix permissions
        # inside docker:
        run: |
          chown builder ../

      - name: Build arch-independent
        run: |
          su builder -c "dpkg-buildpackage -us -uc -A"
          su builder -c "mkdir -p /tmp/debs"
          su builder -c "dcmd mv ../*.changes /tmp/debs/ 2>/dev/null || true"

      - name: Build Debian package
        if: contains(fromJson(inputs.architectures), 'amd64')
        run: |
          su builder -c "dpkg-buildpackage -us -uc -B"
          su builder -c "mkdir -p /tmp/debs"
          su builder -c "dcmd mv ../*.changes /tmp/debs/ 2>/dev/null || true"


  build-arm64:
    needs: update-changelog
    if: contains(fromJson(inputs.architectures), 'arm64')
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      # dpkg-buildpackage -B  (arch-dependent only)
      # uploads artifact: debs-arm64
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Install dependencies
        run: |
          apt-get update
          mk-build-deps --install --remove --tool="apt-get -y --no-install-recommends" debian/control


  release:
    needs: [update-changelog, build-amd64-and-indep, build-arm64]
    if: always() && !cancelled()
    runs-on: ubuntu-latest
    # create GitHub release with all debs
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.update-changelog.outputs.tag_name }}
          files: /tmp/debs/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify-apt-repo:
    runs-on: ubuntu-latest
    needs: [update-changelog, release]
    # trigger apt-repo dispatch
    steps:
      - name: Notify apt-repository
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh api repos/${{ inputs.apt_repo }}/dispatches \
          --method POST \
          --field event_type=new-deb-package \
          --field client_payload[repository]=${{ github.repository }} \
          --field client_payload[run_id]=${{ github.run_id }} \
          --field client_payload[version]=${{ needs.update-changelog.outputs.tag_name }}

          echo "::notice::Triggered apt-repo: https://github.com/${{ inputs.apt_repo }}/actions"
