name: Create a release out of artifacts for debian packages

# out of all artifacts, we take the N groups with debian packages

on:
  workflow_call:
    inputs:

      artifacts:
        description: 'Architectures to build for'
        type: string  # JSON with a list.
        default: 'amd64' # or 'amd64,arm64'

      release:
        description: 'version string'
        type: string


permissions:
  contents: write
  packages: write # Optional, but good if you use GHCR

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # choose
      - name: Set results dir
        run: |
          RESULTS_DIR=$GITHUB_WORKSPACE/results-${{ github.run_id }}
          mkdir -p "$RESULTS_DIR"
          echo "RESULTS_DIR=$RESULTS_DIR" >> $GITHUB_ENV

    # create GitHub release with all debs
      - name: Download amd64 artifacts
        if: contains(fromJson(inputs.artifacts), 'debs-amd64')
        uses: actions/download-artifact@v4
        with:
          name: debs-amd64
          path:  ${{ env.RESULTS_DIR }}
        continue-on-error: true

      - name: Download arm64 artifacts
        if: contains(fromJson(inputs.artifacts), 'debs-arm64')
        uses: actions/download-artifact@v4
        with:
          name: debs-arm64
          path: ${{ env.RESULTS_DIR }}
        continue-on-error: true


      - name: Download arch-indep artifacts
        if: contains(fromJson(inputs.artifacts), 'debs-indep')
        uses: actions/download-artifact@v4
        with:
          name: debs-indep
          path: ${{ env.RESULTS_DIR }}
        continue-on-error: true

      - name: List downloaded files
        run: |
            echo "Files in ${{ env.RESULTS_DIR }}:"
            ls -laR ${{ env.RESULTS_DIR }}
            echo "---"
            find ${{ env.RESULTS_DIR }} -type f | sort

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.update-changelog.outputs.tag_name }}
          files: ${{ env.RESULTS_DIR }}/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
